[RTMP]

listen = 1935

app = "live"

;内容延时, 单位秒
content_latency = 3

[HTTP]

listen = 8080

[COMMON]

;音视频数据包在任务队列中存储的最大时间间隔, 超过这个时间数据包会被丢弃, 单位: 微妙
max_store_time = 500000
;线程数
thread_nums = 4

[LOG]

log_level = 1